### ISSUE TITLE
안녕하세요, 최근 버전 오류 문의드립니다.

### ISSUE THREAD

**Issue by aerongss** [forkonlp/N2H4#100]
선생님 안녕하세요, 패키지를 공유해주셔서 감사합니다.
제 R 버전이 문제인 것인지, 패키지가 깔리지 않아 문의드립니다.
![image](https://user-images.githubusercontent.com/99466132/153546980-7407d00c-cca4-4e59-bc82-3959d942822c.png)
좋은 하루 되세요. 감사합니다.

**Comment by mrchypark** [comment]
안녕하세요, 이슈를 생성해주셔서 정말 감사드립니다. 현재 N2H4는 R 3.2 버전 이상을 요구하고 있습니다만, 출력을 보건데 4.1 버전대를 사용하고 계신 것 같습니다.

혹시 어떤 코드를 실행하신 건지와, sessionInfo()의 결과를 공유해주실 수 있으실까요?

한가지 추가하자면, 현재 cran에서 내려가 있어서 `install.packages()` 함수로 설치할 수 없는 상태로 알고 있습니다.
아래 코드로 동작하는지 확인해주시면 감사하겠습니다.
```
install.packages("N2H4", repos = "https://forkonlp.r-universe.dev")
```

**Comment by aerongss** [comment]
안녕하세요, 현재 4.1.2의 최신버전을 사용하고 있습니다.보내주신 버전으로 깔립니다:) 이후 실행코드는 깃헙 페이지에서 내려져 있는 상태인지요?(인스톨 단계에서 문제가 있어 문의드렸었습니다.)애써 주셔서 감사합니다.예령 드림> sessionInfo()R version 4.1.2 (2021-11-01)Platform: x86_64-w64-mingw32/x64 (64-bit)Running under: Windows 10 x64 (build 19042)Matrix products: defaultlocale:[1] LC_COLLATE=Korean_Korea.949  LC_CTYPE=Korean_Korea.949    LC_MONETARY=Korean_Korea.949[4] LC_NUMERIC=C                 LC_TIME=Korean_Korea.949    attached base packages:[1] stats     graphics  grDevices utils     datasets  methods   base     other attached packages:[1] dplyr_1.0.7        readr_2.1.1        stringr_1.4.0      KoNLP_0.80.2      [5] tidytext_0.3.2     wordcloud_2.6      RColorBrewer_1.1-2loaded via a namespace (and not attached): [1] tidyselect_1.1.1  remotes_2.4.2     purrr_0.3.4       rJava_1.0-6       lattice_0.20-45   [6] testthat_3.1.1    colorspace_2.0-2  vctrs_0.3.8       generics_0.1.1    usethis_2.1.5    [11] SnowballC_0.7.0   hash_2.2.6.1      utf8_1.2.2        blob_1.2.2        rlang_0.4.12     [16] pkgbuild_1.3.1    pillar_1.7.0      glue_1.6.0        withr_2.4.3       DBI_1.1.2        [21] bit64_4.0.5       tau_0.0-24        sessioninfo_1.2.2 lifecycle_1.0.1   munsell_0.5.0    [26] Sejong_0.01       gtable_0.3.0      devtools_2.4.3    memoise_2.0.1     tzdb_0.2.0       [31] callr_3.7.0       fastmap_1.1.0     ps_1.6.0          fansi_0.5.0       tokenizers_0.2.1 [36] Rcpp_1.0.8        scales_1.1.1      cachem_1.0.6      desc_1.4.0        pkgload_1.2.4    [41] fs_1.5.2          bit_4.0.4         hms_1.1.1         ggplot2_3.3.5     stringi_1.7.6    [46] processx_3.5.2    rprojroot_2.0.2   grid_4.1.2        cli_3.1.0         tools_4.1.2      [51] magrittr_2.0.1    tibble_3.1.6      RSQLite_2.2.9     janeaustenr_0.1.5 crayon_1.5.0     [56] pkgconfig_2.0.3   ellipsis_0.3.2    Matrix_1.3-4      prettyunits_1.1.1 assertthat_0.2.1 [61] R6_2.5.1          compiler_4.1.2--------- 원본 메일 ---------보낸사람 : ChanYub Park ***@***.***>받는사람 : forkonlp/N2H4 ***@***.***>참조 : aerongss ***@***.***>, Author ***@***.***>받은날짜 : 2022-02-12 (토) 03:37:46제목 : Re: [forkonlp/N2H4] 안녕하세요, 최근 버전 오류 문의드립니다. (Issue #100)
안녕하세요, 이슈를 생성해주셔서 정말 감사드립니다. 현재 N2H4는 R 3.2 버전 이상을 요구하고 있습니다만, 출력을 보건데 4.1 버전대를 사용하고 계신 것 같습니다.
혹시 어떤 코드를 실행하신 건지와, sessionInfo()의 결과를 공유해주실 수 있으실까요?
한가지 추가하자면, 현재 cran에서 내려가 있어서 install.packages() 함수로 설치할 수 없는 상태로 알고 있습니다.
아래 코드로 동작하는지 확인해주시면 감사하겠습니다.
install.packages("N2H4", repos = "https://forkonlp.r-universe.dev")


—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
You are receiving this because you authored the thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/forkonlp/N2H4/issues/100#issuecomment-1036505248",
"url": "https://github.com/forkonlp/N2H4/issues/100#issuecomment-1036505248",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by mrchypark** [comment]
공유드린 코드는 github 버전의 설치 방법이었습니다. 계속 사용하시면 되겠습니다. 감사합니다.

**Comment by mrchypark** [comment]
@all-contributors please add @aerongss for bug
