### ISSUE TITLE
getComment 오류인것같아 리포트합니다.

### ISSUE THREAD

**Issue by bbserverdown** [forkonlp/N2H4#104]
안녕하세요. 올려주신 코드로 처음 댓글수집을 해보려는 사용자입니다.
적혀있는대로 네이버 기사 링크를 올려서 댓글을 수집하려고하는데.
링크를 바꿔도 계속 같은 댓글이 수집 되더라구요.

`library(N2H4)
comment<-N2H4::getComment(turl="https://n.news.naver.com/mnews/article/001/0013162749?sid=104",
                          pageSize = 100)
comment$contents[[1]]`

이 코드로 프로그램을 돌렸고
"2015 댓글은 없구료..."라는 댓글이 계속 처음에 등장합니다.

**Comment by mrchypark** [comment]
안녕하세요, 이슈 생성해주셔서 감사합니다. 혹시 사용하신 코드 전체를 공유해주실 수 있으신가요?

**Comment by bbserverdown** [comment]
위에 적힌 코드가 전부입니다. comment에다가 기사 댓글 데이터넣고 R studio environment에서 comment 데이터 확인했습니다.

**Comment by bbserverdown** [comment]
[댓글.csv](https://github.com/forkonlp/N2H4/files/8647929/default.csv)

위 comment를 csv로 받은내용입니다.

**Comment by mrchypark** [comment]
@bbserverdown 우선 댓글 수집이 이상한거 같네요. 이슈 생성해주셔서 감사합니다. 한번 살펴보겠습니다.

**Comment by mrchypark** [comment]
어이구 세상에 링크 구조가 바뀌었군요. 알려주셔서 감사합니다.

**Comment by mrchypark** [comment]
@bbserverdown 수정하였습니다. 금일 7시 이후에 

```install.packages("N2H4", repos = "https://forkonlp.r-universe.dev")``` 
로 설치하시면 0.6.2 버전으로 설치 가능하실 겁니다. 이후에 동작 확인하시면 될 것 같습니다.

다시 한번 이슈 공유해주셔서 정말 감사드립니다.

**Comment by bbserverdown** [comment]
수정 감사합니다! 7시 이후에 동작 확인해보겠습니다.

**Comment by mrchypark** [comment]
@all-contributors please add @bbserverdown for bug
