### ISSUE TITLE
getComment 주소형식에 따라서 저장이 안되는 문제 문의 드립니다.

### ISSUE THREAD

**Issue by beajinsu** [forkonlp/N2H4#107]
안녕하세요. 훌륭한 패키지 만들어 주셔서 감사합니다. 
getComment 사용시에 주소형식에 따라 저장이 안되는 문제가 있어서 문의드리고자 합니다.

똑같은 링크로 가는 두개의 주소입니다. 그러나 위의 링크는 아무 댓글도 받아지지 않고 아래의 경우에는 댓글이 잘 받아집니다.
어떤 이유인지 확인해주실 수 있을까요? getContent의 경우에는 두개의 링크 모두 본문이 잘 받아집니다.

comment<-N2H4::getComment(turl="https://news.naver.com/main/read.naver?mode=LSD&mid=sec&sid1=101&oid=037&aid=0000030157", pageSize = 100) 

comment<-N2H4::getComment(turl="https://n.news.naver.com/mnews/article/037/0000030157?sid=101", pageSize = 100)

**Comment by mrchypark** [comment]
안녕하세요, 이슈 생성해주셔서 감사합니다!

댓글을 수집할 때 주소내의 정보를 사용하는 곳이 있는데요.
아래 형태의 주소로 변경된 것을 확인하고 아래 주소의 형식에서 정보를 가져오도록 수정하였습니다.


별도의 질문인데요. 위 형태의 주소도 아직도 사용할 수 있나보군요? 어디서 확보하시나요?

**Comment by beajinsu** [comment]
빠르게 확인 해주셔서 감사합니다! 제가 아직 코드를 돌려보지 않았는데 돌려보는데로 다시 한번 글 남기겠습니다. 

위 형태의 주소는 네이버 뉴스 결과창에서 옵션을 이것저것 만지면서 크롤링 하기 쉬운 형태로 만들면서 얻게 되었습니다.

**Comment by mrchypark** [comment]
그렇군요. 기존 양식도 다시 함께 지원해야 할 수도 있겠네요. 알려주셔서 감사합니다!

**Comment by beajinsu** [comment]
위의 링크의 경우에는 여전히 댓글이 안 받아지네요. 혹시 제가 N2H4 패키지를 제대로 업데이트 하지 않아서 일까요?

**Comment by mrchypark** [comment]
0.6.4 버전을 올리면서 문제를 해결하였습니다. 혹시 문제가 또 있으시다면 언제나 다시 오픈해주세요. 감사합니다.
