### ISSUE TITLE
특정 네이버 링크에서 getContent 함수 오류 관련

### ISSUE THREAD

**Issue by beajinsu** [forkonlp/N2H4#108]
여러 링크에서 본문을 받던 중 getContent 함수가 에러가 나는 네이버 링크를 발견 했습니다.

getContent("https://n.news.naver.com/mnews/article/277/0003204982?sid=106")

UseMethod("xml_find_all")에서 다음과 같은 에러가 발생했습니다:
  클래스 "list"의 객체에 적용된 'xml_find_all'에 사용할수 있는 메소드가 없습니다

아마도 웹페이지의 형식이 네이버 "연애" 홈이라서 그런 것 같은데 한번 확인 부탁드리겠습니다.

**Comment by mrchypark** [comment]
안녕하세요! 이슈 생성해주셔서 정말 감사드립니다.

스포츠랑 연애가 구조가 달라서, 그동안 주소로 체크해서 막아왔었는데,
그러고 보니 주소 체계가 변경되면서 같아진 모양이네요. 스포츠도 확인해봐야 겠습니다.

감사합니다.
