### ISSUE TITLE
위키 설명 함수를 getUrlListbyCategory -> getUrlList 이렇게 바꾸면 동작이 되네요:)

### ISSUE THREAD

**Issue by jaehong-k** [forkonlp/N2H4#111]
위키를 보며 잘 공부하였습니다! 꼼꼼하게 그리고 친절히 설명해주셔서 너무 감사드립니다 :)
한 가지 오류가 있어 수정하면 좋을 것 같아, 글을 남기게 되었습니다.
위키 카테고리를 통한 수집을 따라하던 중 아래 사진과 같은 오류가 났는데,
![image](https://user-images.githubusercontent.com/68909968/178786821-d253f37a-5196-4bab-96a6-0ae42800a740.png)

1. 현재 네이버 url 구조 적용
2. getUrlListbyCategory -> getUrlList 이렇게 바꾸면 동작이 잘 되네요:)
훌륭한 페키지 만들어주심에 감사드립니다! 연구에 많은 도움이 됐습니다

**Comment by mrchypark** [comment]
@kjhkjh95 안녕하세요! 맞습니다. 이번에 수정했는데, wiki 코드를 방치하고 있었네요. 수정하겠습니다.

알려주셔서 감사드립니다.

**Comment by mrchypark** [comment]
위키 수정함.
