### ISSUE TITLE
수집된 뉴스 댓글 중복 문제

### ISSUE THREAD

**Issue by RingPark** [forkonlp/N2H4#137]
안녕하세요.
N2H4를 이용해 네이버 뉴스 댓글 수집하여 텍스트마이닝을 공부하는 대학원생입니다.
유용한 도구를 만들어 주셔서 먼저 감사드립니다.
다만, 몇가지 문제에 있어 질문을 드리고자 합니다.
전체 댓글의 수가 100개가 넘는 뉴스에서 getAllComment 혹은 getComment를 이용하여 전체 댓글을 수집할 때, 댓글이 중복하여 수집되는 문제가 발생합니다.

예를 들어 전체 댓글의 수가 500개라면 1-100번 댓글이 정상적으로 수집되는데, 101-200번, 201-300번, 301-400번, 401-500번 댓글을 1-100번 댓글이 중복하여 전체 댓글의 수 500개에 맞춰집니다... 같은 댓글을 5개씩 수집해서 수만 맞추고 있는데요...

해결방안에 대해 도움을 요청드립니다.

comments <- getAllComment("https://n.news.naver.com/mnews/article/023/0003712918")
-네이버 뉴스 중 임의로 하나의 기사에서 전체 댓글을 수집했는데, 같은 댓글을 중복하여 수집하여 전체 댓글의 수에 맞춰 수집되는 오류가 발생합니다.

**Comment by mrchypark** [comment]
안녕하세요 이슈 작성해주셔서 정말 감사드립니다. 예상되는 코드 문제가 있어서 해결하고 공유드리겠습니다.

**Comment by mrchypark** [comment]
async 동작을 지원해야 해서, 기반 패키지를 httr2 로 변경.

**Comment by mrchypark** [comment]
https://github.com/forkonlp/N2H4/issues/134

이거 함께 처리

**Comment by mrchypark** [comment]
page 파람이 동작하지 않음. 이 지정 부분이 동작하지 않으면 순차 요청할 수 밖에 없음.

**Comment by mrchypark** [comment]
확인 완료. 순차 요청만 동작함.

**Comment by mrchypark** [comment]
수정 완료. 

@RingPark 개발 버전으로 사용하시면 동작할 겁니다. 0.7.2 입니다. 감사합니다.

**Comment by RingPark** [comment]
감사합니다. 기존 버전 삭제 후 말씀해주신 개발 버전 설치하니 정상적으로 전체 댓글 수집이 됩니다. 정말 감사합니다.

**Comment by mrchypark** [comment]
https://github.com/all-contributors please add @RingPark for bugs

**Comment by mrchypark** [comment]
@all-contributors please add @RingPark for bugs
