### ISSUE TITLE
안녕하세요 덕분에 요긴하게 잘 쓰고 있습니다.

### ISSUE THREAD

**Issue by siso1986** [forkonlp/N2H4#14]
비영리법인입니다. 급하게 프로젝트가 있어 댓글 기능도 쓸려고 합니다.
R 초보자라 많이 헤메고 있습니다. 
어떻게 소스코드를 구해 그대로 집어 넣었더니
setwd("C:/news/naverNewsParser-master/naverNewsParser-master")
> if (!require("devtools")) install.packages("devtools")
필요한 패키지를 로딩중입니다: devtools
> devtools::install_github("forkonlp/N2H4")
Skipping install of 'N2H4' from a github remote, the SHA1 (eb56f2d2) has not changed since last install.
  Use `force = TRUE` to force installation
> install.packages("iterators")
Installing package into ‘C:/Users/wongi/Documents/R/win-library/3.3’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.3/iterators_1.0.8.zip'
Content type 'application/zip' length 316188 bytes (308 KB)
downloaded 308 KB

package ‘iterators’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\wongi\AppData\Local\Temp\RtmpAdGq28\downloaded_packages
> library(N2H4)
> url <- readLines("url.csv")
> for(i in 1:10){
+     
+     t <- Sys.time()
+     cat(t,"\n")
+     t <- strftime(t,"%Y-%m-%d %H:%M:%S")
+     starttime[i] <- t
+     comm <- getComment(turl = url[i])
+     comments <- comm$result$count$comment
+     comm <- getComment(turl = url[i] , pageSize = comments, page = 1)
+     lst <- comm$result$commentList
+     lst <- as.data.frame(lst)
+     lst <- lst[,-46]
+     
+     write.csv(lst, paste("commentscollect",i,".csv",sep=""))
+ }
1484088578 
Error in starttime[i] <- t : object 'starttime' not found
> 
> filename <- vector()
> for(i in 1:10){
+     filename[i] <- paste("commentscollect",i,".csv",sep="")
+ }
> 
> timelist <- cbind(filename,starttime)
Error in cbind(filename, starttime) : object 'starttime' not found
> write.csv(timelist, "timelist.csv")
Error in is.data.frame(x) : object 'timelist' not found

이렇게 3번의 에러가 나오네요 ㅠㅠ 저 딴에는 이것저것 시도해 보았지만 너무 초보자라 역부족입니다.
잘 만들어 주셔서 잘 쓰고 싶은데 잘 안되네요
바쁘시겠지만 이럴땐 어떻게 해야 하는지 알려주시면 감사하겠습니다~
덧붙여 다른 코멘트를 보니 아직 예시를 안만드셨다고 하셨는데 그럼 지금 패키지로 특정 키워드 크롤링도 가능한 건가요?
잘 쓰고 싶어서 열심히 매달려봅니다. 부탁드립니다.

**Comment by mrchypark** [comment]
@siso1986 안녕하세요, 혹시 url에 어떤 것이 들어 있는지 알 수 있을까요?

**Comment by siso1986** [comment]
안녕하세요. 질문을 드려놓고 소개가 늦었습니다.
 
저희는 비영리 정치통계연구소 상수동 전략그룹입니다. 
 
이번에 19대 대선을 앞두고 웹상에서 실시간으로 생산되는 정치 주체별 자극과 생산데이터, 이에 따른 대중의 반응방향과 그 크기를 더해서 민심변화의 양상과 폭을 예측해보는 프로젝트를 준비중에 있습니다.  
 
그러자면 우선 정치뉴스 수집과 2차적으로는 특정 키워드를 가진 뉴스 수집 , 마지막으로는 뉴스의 댓글, 공감도 수집이 필요합니다.
 
데이터 수집도구로서 만들어주신 프로그램이 저희에게 꼭 맞아 열심히 활용하고자 했지만 R에 대한 이해도가 많이 부족하여 이렇게 질문을 드렸습니다.   
 
url.csv 파일은 N2H2 패키지를 사용하여 생성되는 urllist 파일을 축약 편집한 파일입니다. 
 
첨부드린 파일제목 url 이 질문에 인용한 코딩에 사용된 파일입니다.
 
모두 네이버 뉴스 url 입니다.
 
실제로 저희가 분석에 활용하고 싶은 파일은 url2와 같은 파일입니다. 
 
바쁘신 와중에도 답변 주셔서 감사합니다. 
 
저희 홈페이지는 www.sangsoo.org이며 사무실 위치는 합정, 제 연락처는 010-5778-0921입니다.  
 
   
-----Original Message-----

**Comment by mrchypark** [comment]
우선 에러가 난 부분을 보면 starttime[i] <- t 이렇게 값을 startime에 넣으려면 그 전에 선언해주어야 합니다. for문 시작하기 전에 starttime<-c() 를 추가하시면 좋을 듯 합니다. 두번째 에러도 starttime이 에러가 나면서 변수가 없으니 난 에러이고, 세번째도 마찬가지로 두번째 에러 때문에  timelist가 없어서 생긴 에러 같습니다. 자문이 필요하시면 mrchypark@gmail.com 으로 연락주시면 감사하겠습니다. 감사합니다.

**Comment by mrchypark** [comment]
연락주셔서 감사합니다. 오늘 피드백 주신 부분은 프로젝트에 작성해두었습니다. 추가하고 반영해 나가겠습니다. 감사합니다.

**Comment by siso1986** [comment]
개발자님 안녕하세요.
 
일전에 뉴스크롤링 건 관련하여 개발자님 회사 앞에서 직접 뵈었던
 
비영리법인 상수동전략그룹에 조수운입니다.
 
바쁘신 일은 잘 마무리 하셨는지요?
 
저희는 주신 도움에 힘 입어 크롤링 건은 잘 마무리하였습니다. 
 
좋은 인연 식사 대접하면서 이런저런 이야기 함께 하고 싶은데 시간 한번 내어 주실 수 있으신가요?
 
저는 이번주는 금요일 저녁시간만 빼고 괜찮습니다. 다음주도 언제든 좋습니다.
 
스케쥴 보시고 연락부탁드립니다.  
-----Original Message-----
