### ISSUE TITLE
getcomment 질문드립니다.

### ISSUE THREAD

**Issue by kanakan11** [forkonlp/N2H4#18]
현재 getcomment를 사용할 경우 pagesize가 100개가 넘어가면 100개까지 긁어오더라구요 확인 부탁드립니다.

**Comment by mrchypark** [comment]
네 맞습니다. 그럴 경우 pagesize를 조정하시면 됩니다. 지금 기본으로 100으로 되어 있는데 더 설정하셔도 됩니다.

**Comment by kanakan11** [comment]
getComment(turl = url , pageSize = 1000, page = 1) 으로 실행하는 경우에 100개까지 긁히는데 파라미터를 수정해줘야하는 다른 부분이 있는건가요?

**Comment by mrchypark** [comment]
음? 혹시 url을 주실 수 있으신가요

**Comment by kanakan11** [comment]
http://news.naver.com/main/read.nhn?mode=LSD&mid=shm&sid1=100&oid=055&aid=0000499453
입니다~

**Comment by mrchypark** [comment]
안녕하세요, 저도 이제 알았네요. api가 최대 100개 까지만 제공하는 모양입니다. 뒤에 page 숫자를 바꾸시면 다음 댓글들을 가져오실 수 있으니 100개 기준으로 위에 page수를 올리면서 수집하셔야 할 듯 합니다. 감사합니다.

**Comment by kanakan11** [comment]
넵 답변 감사합니다~
