### ISSUE TITLE
예외 페이지 문제

### ISSUE THREAD

**Issue by kwanhong66** [forkonlp/N2H4#19]
안녕하세요

코드를 수정하여 테스트 하던 도중, 

```
while(class(tem)=="try-error"){
            tem<-try(getContent(newslink), silent = TRUE)
            print(paste0("try again: ",newslink))
}
```

이 부분에서 걸려 계속 에러만 출력하는 상황이라 확인해보았더니 페이지 문제가 있는 것 같습니다.

http://news.naver.com/main/read.nhn?mode=LS2D&mid=shm&sid1=100&sid2=264&oid=003&aid=0007761134

에러를 출력하게 된 페이지의 URL은 위와 같습니다.
위 페이지로 접속하여 보면, 기존에 코드가 수집하는 뉴스 리스트 쪽이 아니라 스포츠 섹션 쪽이라 페이지 구성이 달라 id="articleBodyContents"를 가진 div가 없어서 수집에 실패하는 것으로 생각됩니다.

혹시, 이런 이슈를 경험한 적 있으신가요?
해결 방법으로는 while 문에서 불러오기 성공할 때까지 반복하는 것이 아니라, 횟수제한을 둔다거나
해당 페이지와 같은 case도 수집 코드를 추가하는 것 정도 떠오르는데 적절한 처리 방법에 대한 고민이 필요할 것 같습니다

감사합니다 :)

**Comment by mrchypark** [comment]
@kwanhong66 안녕하세요 피드백 주셔서 감사합니다! 해당링크 들어가보니 sports 뉴스 쪽이고, 스포츠 뉴스는 페이지 모양이 달라서 아직 대응하지 못했습니다. url에서 리다이렉 하는 모양인데, 기능상에 리다이렉 주소를 가져와서 패스하는 기능을 구현해놨던거 같은데 이상하네요.ㅠ_ㅠ 우선은 카운트를 추가해서 5회가 넘어가면 빠지는 형태로 재구성해야 할 듯 합니다. 이슈 주셔서 감사합니다!

**Comment by mrchypark** [comment]
예제 코드에 반영해 두었습니다. 혹시 문제가 있으면 알려주세요 감사합니다. 👍
