### ISSUE TITLE
Failed for package 'N2H4'

### ISSUE THREAD

**Issue by YJKimCoffee** [forkonlp/N2H4#2]
Thank you very much for your work. 
I'm having a problem from the start, because I cannot load your package.

When I load "pacman" package, it works until then, but when I type 

pacman::p_load_gh("mrchypark/N2H4")

the following message appears and I cannot use/install your work.

> pacman::p_load_gh("mrchypark/N2H4")
> - installing _source_ package 'N2H4' ...
>   *\* R
>   *\* demo
>   *\* preparing package for lazy loading
>   Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
>   there is no package called 'bitops'
>   ERROR: lazy loading failed for package 'N2H4'
> - removing 'C:/Users/myname/Documents/R/win-library/3.3/N2H4'
>   Error : Command failed (1)
>   Warning message:
>   In pacman::p_load_gh("mrchypark/N2H4") : 
>   Failed to install/load:
>   mrchypark/N2H4

Thank you so much!

**Comment by mrchypark** [comment]
Thank you to notice me.
I'm not sure when i fix this.
But I'm trying to fix this asap.

**Comment by YJKimCoffee** [comment]
Thank you very much. As I'm trying other things, I think it might have been my computer's environmental problem. Don't push yourself too hard.

**Comment by mrchypark** [comment]
I did minor update for this issue.
please check.
thank you.
