### ISSUE TITLE
함수들의 test 코드 페이지가 필요합니다.

### ISSUE THREAD

**Issue by soeque1** [forkonlp/N2H4#29]
testthat을 사용하면 좋을 것 같아요

**Comment by mrchypark** [comment]
@soeque1 네 조언 감사드립니다. 아직 제가 사용법을 잘 몰라서 적용 못하고 있습니다.

**Comment by mrchypark** [comment]
@soeque1 어설프게 반영해봤습니다. 전부 작성하진 못했지만 조금씩 습관을 들여야 겠네요. 이게 함수 단위 뿐만 아니라 조합시 결과물도 반영하면 좋겠다 싶어 고민중입니다. 계속 미루고 있었는데 지적해주셔서 감사합니다.
