### ISSUE TITLE
관련 뉴스 크롤링 제한

### ISSUE THREAD

**Issue by ccwon77** [forkonlp/N2H4#4]
안녕하세요. 네이버 뉴스 크롤러에 대한 문의 드립니다.

특정 기간동안 검색어 쿼리를 통해 N2H4에서 가져오는 뉴스 기사 건수와
동일한 기간과 동일한 검색어 쿼리를 활용하여 네이버 뉴스 페이지에서 검색한 기사 건수가 다른 것 같습니다.

네이버 뉴스 페이지에 있는 언론 기사만 가져오는 건 알겠는데,
아래 그림처럼 관련 뉴스로 숨어 있는 기사는 가져오지 않는 듯 합니다.

![20160902171146](https://cloud.githubusercontent.com/assets/16700486/18197085/5df6960e-7130-11e6-88c1-1afca7d7707b.png)

관련 뉴스로 숨어 있는 기사까지 가져오려면 어떤 코드를 활용해야 하는지요?

**Comment by mrchypark** [comment]
이렇게 피드백 주셔서 감사합니다.
네 맞습니다. 쿼리를 통해 가져오는 기사는 관련뉴스까지는 수집하지 않는 방향으로 설계했습니다.
제가 실력이 부족해서 그것까지 고려해서 짜는건 시간이 더 걸려서 우선 만들었습니다.
getUrlListByQuery  명령어를 수정하시면 되는데, 
rvest 패키지를 사용하실 줄 알아야 합니다.
N2H4 자체는 rvest와 httr 패키지를 활용한 네이버 뉴스 기사 페이지 크롤링 코드를 정리한 것이라고 보면 됩니다.

숨은 기사까지 가져오는 건 마일스톤에 반영해보도록 하겠습니다.
감사합니다.
