### ISSUE TITLE
뉴스생산량 검색시의 에러관련 

### ISSUE THREAD

**Issue by richardyhong** [forkonlp/N2H4#45]
안녕하세요~
향후 잘 사용해보고자 열심히 연습해보고 있습니다.

몇가지 질문을 드릴려고 합니다.

먼저 아래의 예와 같이 입력하였습니다. 
strDate<-"2016-11-01"
endDate<-"2016-12-30"
qs<-c("질병모델동물","질환모델동물","실험동물&바이오이미징")
dat<-c()
for(q in qs){
  print(q)
  tem <- getNewsTrend(q,strDate,endDate)
  dat<-rbind(dat,cbind(data.frame(q=q,tem)))
}

## 참고로 예제에   dat<-rbind(dat,cbind(data.frame(q=q,tem))게 되어있어서 ")"한개 빠져 있더라구요

질문드릴려고 하는 것은 이렇게 실행했을 때 아래와 같은 에러가 떳습니다.
[1] "질병모델동물"
Error in strsplit(result$cnt, "/") : 문자형을 가지지 않는 인자입니다
어떻게 해결하면 좋을 런지요?

둘째는 이게 그려졌다고 할때 검색기간을 장기간으로 했을 경우 혹시 
월단위로 cnt를 count해서 표로 쉽게 할 수 있는 방안은 없을까요?

감사합니다.

**Comment by mrchypark** [comment]
@richardyhong  안녕하세요 괄호 지적해 주셔서 감사합니다. 또한 방금 확인해 봤는데, 당일 기간내에 검색량이 없을 경우가 있어서 그부분이 0건 처리가 안된거 같습니다. 함수내 버그도 찾아주셔서 감사합니다. fix해서 댓글 다시 달도록 하겠습니다. 감사합니다.

**Comment by mrchypark** [comment]
@richardyhong 안녕하세요. 관련 문제에 있어서 검색량이 0인 경우 에러 없이 0으로 표기되도록 수정하였습니다. 감사합니다. 월단위로 카운트 하는 방식은 데이터를 정리하는 방법을 찾아보셔야 할 것 같습니다. 지금 모양으로는 lubrdate 같은 패키지를 이용해서 년월일 컬럼을 년월로 조정하시고 groupby 로 년월 sum을 수행하시는 방법이 있을 것 같습니다.  데이터 처리를 위해서는 dplyr 이나 data.table, reshape2 같은 패키지를 추천드립니다. 감사합니다.
