### ISSUE TITLE
MaxPage를 못찾네요

### ISSUE THREAD

**Issue by richardyhong** [forkonlp/N2H4#57]
안녕하세요 박찬엽 선생님

N2H4 유용하게 사용하고 있습니다.
한두달 전 쯤에 사용하다가 기간을 변경하여야 할 필요성이 있어서 다시 해보니까
아래와 같이 MaxPage를 못찾는데요
혹시 devtool 버전에러나 뭐 그런걸까요?

귀찮게 해드려 죄송해요...

> library(N2H4)
> q<-"독성시험"
> tar <- getQueryUrl(q, startDate=as.Date(Sys.time())-30, endDate=as.Date(Sys.time()))
> maxPage <- getMaxPageNum(tar)
> for (i in 1:maxPage){
+     tarp <- paste0(tar,"&page=",i)
+     newsList<-getUrlListByQuery(tarp)
+     newsData<-c()
+     for (newslink in newsList$news_links){
+         tryi<-0
+         tem<-try(getContent(newslink), silent = TRUE)
+         while(tryi<=5&&class(tem)=="try-error"){
+             tem<-try(getContent(newslink), silent = TRUE)
+             tryi<-tryi+1
+             print(paste0("try again: ",newslink))
+         }
+         if(class(tem$datetime)[1]=="POSIXct"){
+             newsData<-rbind(newsData,tem)
+         }
+     }
+     dir.create("./data",showWarnings=F)
+     write.csv(newsData, file=paste0("./data/news_",q,"_",i,".csv"),row.names = F)
+ }
Error in 1:maxPage : NA/NaN argument

**Comment by mrchypark** [comment]
안녕하세요 혹시 sessionInfo() 를 보여주실 수 있으신가요?

**Comment by richardyhong** [comment]
이렇게 되어 있습니다. 
> sessionInfo() 
R version 3.4.1 (2017-06-30)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=Korean_Korea.949  LC_CTYPE=Korean_Korea.949   
[3] LC_MONETARY=Korean_Korea.949 LC_NUMERIC=C                
[5] LC_TIME=Korean_Korea.949    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] N2H4_0.4.6.3    devtools_1.13.3

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.12   XML_3.98-1.9   digest_0.6.12  withr_2.0.0    bitops_1.0-6  
 [6] R6_2.2.2       jsonlite_1.5   git2r_0.19.0   magrittr_1.5   httr_1.3.1    
[11] stringi_1.1.5  curl_2.8.1     xml2_1.1.1     tools_3.4.1    stringr_1.2.0 
[16] selectr_0.3-1  RCurl_1.95-4.8 compiler_3.4.1 rvest_0.3.2    memoise_1.1.0

**Comment by mrchypark** [comment]
@richardyhong 인코딩 문제인 것 같습니다. q<-URLencode(enc2utf8("독성시험")) 으로 바꿔보세요!

**Comment by mrchypark** [comment]
는 무슨 네이버 서비스가 바뀌어서 동작을 다르게 하네요. 좀 고쳐야 할 것 같습니다. 이슈 만들어 주셔서 감사해요!

**Comment by richardyhong** [comment]
감사합니다.

**Comment by mrchypark** [comment]
@richardyhong 안녕하세요, 확인해 봤는데, 빠르게 반영하기는 어려울 것 같습니다.
기존에 카테고리 페이지나 과거 검색페이지는 페이지를 뛰어 넘어서 실행하면 가장 최근 페이지로 보여줘서 그걸 이용해서 맥스 페이지를 찾았었는데요, 지금은 페이지 없음으로 호출해서 꽤 많은 요청을 해야 하는 문제가 생겼습니다. 검색 페이지 상단에 검색건이 있어서 그걸 가져와서 테스트 하는 형태로 진행해야 할 것 같은데, 제가 작업하는데 시간이 걸리겠네요. 상황 파악은 되었습니다. 그리고 변경된 상황에 맞게 getQuearyUrl 함수를 수정했습니다. 감사합니다.

**Comment by mrchypark** [comment]
https://github.com/forkonlp/N2H4/pull/61

내용을 수정했습니다.
확인부탁드립니다. 감사합니다.

search page 쪽의 max page 기능을 변경했는데, 제 테스트 상은 문제가 없네요.

**Comment by richardyhong** [comment]
아래와 같이 Test 해봤습니다.

if (!require("devtools")) install.packages("devtools")
devtools::install_github("forkonlp/N2H4")
library(N2H4)
if (!require("ggplot2")) install.packages("ggplot2")
library(ggplot2)

strDate<-"2017-8-1"
endDate<-"2017-8-31"

qs<-c("상수도")

dat<-c()
for(q in qs){
  print(q)
  tem <- getNewsTrend(q,strDate,endDate)
  dat<-rbind(dat,cbind(data.frame(q=q,tem)))
}

ggplot(dat,aes(x=date,y=cnt,group=q,color=q)) + geom_line()

write.csv(dat, "newstrend.csv", row.names=TRUE)

네이버 자체에는 많은 신문기사가 뜨지만 R로는 하나도 못잡아 내는 것같습니다 
 head(dat)
       q       date cnt
1 상수도 2017-08-01   0
2 상수도 2017-08-02   0
3 상수도 2017-08-03   0
4 상수도 2017-08-04   0
5 상수도 2017-08-05   0
6 상수도 2017-08-06   0;

**Comment by mrchypark** [comment]
이걸로 한번 해보시겠어요?? getNewsTrend()도 수정해야 겠네요... getQueryUrl()함수에 의존성이 있던 함수인데 검색 페이지 주소 모양이 많이 바뀌었더라구요. getQueryUrl() 함수도 수정해야 겠네요.

```
# install.packages("selectr")
library(curl)
library(rvest)
# install.packages("devtools")
# devtools::install_github("forkonlp/N2H4")
library(N2H4)

options(stringsAsFactors = F)

success <- function(res){
  cat("Request done! Status:", res$status, "\n")
  #res$content<-iconv(rawToChar(res$content),from="CP949",to="UTF-8")
  res$content<-rawToChar(res$content)
  data <<- c(data, list(res))
}
failure <- function(msg){
  cat("Oh noes! Request failed!", msg, "\n")
}


strDate<-as.Date("2017-08-01")
endDate<-as.Date("2017-08-31")

strTime<-Sys.time()
midTime<-Sys.time()

qlist<-c("상수도")
for (i in 1:length(qlist)){
  dir.create("./data",showWarnings=F)
  dir.create(paste0("./data/news_",qlist[i]),showWarnings=F)
  
  for (date in strDate:endDate){
    date<-as.character(as.Date(date,origin = "1970-01-01"))
    dateo<-gsub("-",".",date)
    dated<-gsub("-","",date)
    print(paste0(date," / ",qlist[i], "/ start Time: ", strTime," / spent Time: ", Sys.time()-midTime," / spent Time at first: ", Sys.time()-strTime))
    midTime<-Sys.time()
    pageUrli<-paste0("https://search.naver.com/search.naver?where=news&query=",qlist[i],"&ie=utf8&sm=tab_srt&sort=1&photo=0&field=0&reporter_article=&pd=3&ds=",dateo,"&de=",dateo,"&docid=&nso=so%3Ar%2Cp%3Afrom",date,"to",date,"%2Ca%3Aall&mynews=0&mson=0&refresh_start=0&related=0")  
    trym<-0
    max<-try(getMaxPageNum(pageUrli, search=T), silent = T)
    while(trym<=5&&class(max)=="try-error"){
      max<-try(getMaxPageNum(pageUrli, search=T), silent = T)
      Sys.sleep(abs(rnorm(1)))
      trym<-trym+1
      print(paste0("try again max num: ",pageUrli))
    }
    if(max=="no result"){
      print("no naver news links this time")
      next
    }
    for (pageNum in 1:max){
      start<-(pageNum-1)*10+1
      print(paste0(date," / ",qlist[i], "/ start Time: ", strTime," / spent Time: ", Sys.time()-midTime," / spent Time at first: ", Sys.time()-strTime))
      midTime<-Sys.time()
      pageUrl<-paste0(pageUrli,"&start=",start)
      tryp<-0
      newsList<-try(getUrlListByQuery(pageUrl), silent = T)
      while(tryp<=5&&class(newsList)=="try-error"){
        newsList<-try(getUrlListByQuery(pageUrl), silent = T)
        Sys.sleep(abs(rnorm(1)))
        tryp<-tryp+1
        print(paste0("try again max num: ",pageUrl))
      }
      if(newsList$news_links[1]=="no naver news"){ 
        print("no naver news links this time")
        next
      }
      
      pool <- new_pool()
      data <- list()
      sapply(newsList$news_links, function(x) curl_fetch_multi(x,success,failure))
      res <- multi_run()
      
      if( identical(data, list()) ){
        pool <- new_pool()
        data <- list()
        sapply(newsList$news_links, function(x) curl_fetch_multi(x,success,failure))
        res <- multi_run()
      }
      
      closeAllConnections()
      
      loc<-sapply(data, function(x) grepl("^http://news.naver",x$url))
      cont<-sapply(data, function(x) x$content)
      cont<-cont[loc]
      
      if(identical(cont,character(0))){ 
        print("no naver news links this time")
        next
      }
      
      titles<-unlist(lapply(cont,function(x) getContentTitle(read_html(x))))
      bodies<-unlist(lapply(cont,function(x) getContentBody(read_html(x))))
      presses<-unlist(lapply(cont,function(x) getContentPress(read_html(x))))
      datetime<-lapply(cont,function(x) getContentDatetime(read_html(x))[1])
      datetime<-sapply(datetime, function(x) (as.character(x)[1]))
      edittime<-lapply(cont,function(x) getContentDatetime(read_html(x))[2])
      edittime<-sapply(edittime, function(x) (as.character(x)[1]))
      
      urls<-sapply(data, function(x) x$url)
      urls<-urls[loc]
      
      datC<-data.frame(titles,urls,presses,datetime,edittime,bodies)
      
      write.csv(datC, file=paste0("./data/news_",qlist[i],"/news_",date,"_",pageNum,".csv"),row.names = F, fileEncoding="UTF-8")
      
    }
  }
}
```

**Comment by richardyhong** [comment]
네 GetNews 옛날 보다 효율성이 많이 떨어지는 것같아 아쉽구요.

데이타에서 한글이 깨지는데 인코딩의 문제가 있는 것같습니다. 

고생이 많으십니다. 감사합니다.

**Comment by SEUNG-HYE** [comment]
도움이 되실지 모르겠습니다만, 저도 한글이 깨졌다고 생각했는데 메모장으로 열면 안 깨져있고, 한셀에서도 안 깨지고 제대로 열리더라고요^^ 엑셀에서 왜 깨지는 지는 모르겠습니다ㅠㅠ

**Comment by mrchypark** [comment]
@SEUNG-HYE  @richardyhong 안녕하세요, 인코딩은 UTF-8로 저장하고 있습니다. 엑셀에서는 기본 인코딩이 cp949라 그냥 열면 깨지는 문제가 있거든요. 저장 부분에 인코딩 옵션을 빼시거나 엑셀에서 UTF-8로 불러오시면 문제없이 보실 수 있을 겁니다.

**Comment by hymnkim** [comment]
좋은 도구 만들어 주셔서 감사합니다. 몇 가지 해결되지 않는 부분이 있어 질문드립니다.
먼저, 설정한 날짜에 키워드 관련 뉴스가 없으면 max페이지를 잡지 못한다고 나옵니다. 처음에 max페이지를 찾을 수 없다고 나오던 키워드가 뉴스 있는 날짜로 설정하자 크롤링하기 시작했습니다.
두번째, 뉴스 게시일이 연속되지 않으면 읽어 오는데 실패하는 것을 보였습니다. 예를 들어, 7월 5일, 4일, 3일 연속된 뉴스는 읽을 수 있었지만 그 다음 날짜가 6월 15일 로 나타날 때 크롤링을 멈췄습니다.
마지막으로 csv파일로 저장될 때 5개의 뉴스만 저장되지 않고, 키워드 검색시 키워드 전체의 뉴스가 한 파일에 저장되는 방법이 궁금합니다. 날짜는 이미 csv 파일 안에 저장되어 있기 때문에 굳이 파일을 나눌 필요가 없다고 생각됩니다.
감사합니다.

**Comment by mrchypark** [comment]
@SEUNG-HYE  https://m.blog.naver.com/PostView.nhn?blogId=carrotcarrot&logNo=220662217154&proxyReferer=https%3A%2F%2Fwww.google.co.kr%2F 이거 참고하세요!

**Comment by changhyub** [comment]
@mrchypark 안녕하세요. 
비슷한 문제인지 모르겠으나 제가 R에 익숙치 않아 아마 이슈라기보다 질문이 아닐까 해서 문의드립니다.
검색어를 기준으로 뉴스와 댓글을 가져오는 예제코드를 돌려보려는데 
Max Number를 가져오는 부분에서 
'max : 강제형변환에 의해 생성된 NA 입니다' 와 같은 에러가 발생합니다.

Max Number를 임의로 1로 주고 넘어가더라도 getUrlListByQuery 에서 정상적으로 값을 가져오질 못하네요ㅠ
필요한 package나 library가 정상적으로 세팅되지 않은 게 아닐까 싶은데 혹시 도움을 좀 요청드릴 수 있을까 해서 이슈 남깁니다. 감사드립니다.

참고를 위해 sessionInfo()를 첨부합니다.
> sessionInfo()
R version 3.4.3 (2017-11-30)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.3 LTS

locale:
 [1] LC_CTYPE=ko_KR.UTF-8       LC_NUMERIC=C               LC_TIME=ko_KR.UTF-8        LC_COLLATE=ko_KR.UTF-8    
 [5] LC_MONETARY=ko_KR.UTF-8    LC_MESSAGES=ko_KR.UTF-8    LC_PAPER=ko_KR.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=ko_KR.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] N2H4_0.4.6.6         rvest_0.3.2          xml2_1.1.1           curl_3.1             RevoUtils_10.0.8     RevoUtilsMath_10.0.1

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.14    withr_2.1.1     digest_0.6.13   bitops_1.0-6    R6_2.2.2        jsonlite_1.5    git2r_0.20.0   
 [8] magrittr_1.5    httr_1.3.1      stringi_1.1.6   devtools_1.13.4 tools_3.4.3     stringr_1.2.0   selectr_0.3-1  
[15] RCurl_1.95-4.9  yaml_2.1.16     compiler_3.4.3  memoise_1.1.0
