### ISSUE TITLE
getAllComment function

### ISSUE THREAD

**Issue by ghost** [forkonlp/N2H4#58]
안녕하십니까, 선생님.

크롤링 소스코드를 감사하게 사용하고 있는 학생입니다.

사용 용도상 현재까지는 getComment.R만 사용하고 있었는데요.
getAllComment function의 실행에 문제가 있어서 질문을 여쭙고자 글을 남깁니다.

올려주신 함수 정의 코드는

```

getComment <- function(turl = url, pageSize = 10, page = 1, sort = c("favorite", "reply", "old", "new")) {
    sort <- sort[1]
    tem <- stringr::str_split(turl, "[=&]")[[1]]
    oid <- tem[grep("oid", tem) + 1]
    aid <- tem[grep("aid", tem) + 1]
    url <- paste0("https://apis.naver.com/commentBox/cbox/web_naver_list_jsonp.json?ticket=news&templateId=view_politics&pool=cbox5&lang=ko&country=KR&objectId=news",
        oid, "%2C", aid, "&categoryId=&pageSize=", pageSize, "&indexSize=10&groupId=&page=", page, "&initialize=true&useAltSort=true&replyPageSize=30&moveTo=&sort=",
        sort)
    con <- httr::GET(url,
                     user_agent("N2H4 using r by chanyub.park mrchypark@gmail.com"),
                     httr::add_headers(Referer = turl))
    tt <- httr::content(con, "text")
    tt <- gsub("_callback", "", tt)
    tt <- gsub("\\(", "[", tt)
    tt <- gsub("\\)", "]", tt)
    tt <- gsub(";", "", tt)
    tt <- gsub("\n", "", tt)
    data <- jsonlite::fromJSON(tt)
    print(paste0("success : ", data$success))
    return(data)

}
```

그리고 

```

getAllComment <- function(turl = url)
{
  temp=getComment(turl,pageSize=1,page=1,sort="favorite")
  numPage=ceiling(temp$pageModel$totalRows/100)
  comments=sapply(1:numPage,getComment,turl=url,pageSize=100,sort="favorite")
  commentList=comments[10,]
  commentList=do.call(rbind, lapply(commentList, data.frame, stringsAsFactors=FALSE))
  return(comments=commentList)
}
```

이 둘인데요. getComment function은 아무 문제 없이 잘 됩니다.
그런데 pagesize는 크롤링하는 댓글 갯수이던데 page는 정확히 어떤 의미인지 여쭤볼 수 있을까요?
이런저런 parameter를 변경해 봤을 때 크롤링 댓글 수 최대가 100개인 것 같은데 그것은 어떤 이슈에 
따른 것인 지, pagesize 100 page 3 이런식으로 300개를 가져오는 등
그 이상이 불가능한 것인지도요..
크롤링 초보의 수준이라 사용은 하되 정확한 코드 내용을 파악하지 못하여 기초적인 질문 드림을 양해해 주시기 바랍니다.

그리고 getAllComment 함수가 돌아가지 않아 구성을 살펴보았는데요.
우선은  numPage=ceiling(temp$pageModel$totalRows/100)
이부분이 numPage=ceiling(temp$result$pageModel$totalRows/100)
같습니다. 댓글이 가령 294일때 100으로 나눠 2.94 를 반올림하여
3페이지를 크롤링한다는 의미라고 생각되는데 dataframe경로를 잘못 받은 듯 합니다.

그런데 이를 수정해도 돌아가지 않아서 오타줄 밑의 코드들도 살펴 보았는데요..
예를들면 sapply가 잘 적용된 것이 맞는지 등등을요..
잘못된 부분이 있다면 찾아내어 말씀드려 코드 기여를 해드리고 싶었지만
위에 말씀드린 바와 같이 개인적으로 getComment 자체도 전체 알고리즘을 이해하고 있지 못해
정확히 어떤 이유로 함수가 안돌아가는지 찾아낼 수가 없었습니다.

이에 getAllComment 함수에 대한 문의를 드리고자 이슈에 글을 남깁니다.

바쁘실 텐데 긴 interruption으로 번거롭게 해 드려 죄송합니다.
혹시 가능하시다면 살펴봐주시길 부탁드리겠습니다. 감사합니다.

**Comment by mrchypark** [comment]
@thkim1638 안녕하세요 이슈 등록해주셔서 감사합니다. 우선 제가 성급하게 getAllComment()를 만들었던 점이 있고, 그 이후에 제가 관리를 못했었네요. 문제 알려주신 부분은 확인해보겠습니다 감사합니다!

**Comment by mrchypark** [comment]
@thkim1638 안녕하세요 기능 수정했는데 확인해봐주시겠어요? 감사합니다.

**Comment by ghost** [comment]
미처 답글을 달지 못했었습니다. 너무 감사드립니다!

**Comment by mrchypark** [comment]
@thkim1638 수정된 기능이 잘 동작된다는 말씀이시죠?ㅎㅎ 저야말로 감사합니다.
