### ISSUE TITLE
'검색어 기반 뉴스 수집' 질문 드립니다.

### ISSUE THREAD

**Issue by SEUNG-HYE** [forkonlp/N2H4#60]
안녕하세요. 크롤링을 막 배우기 시작한 학생입니다.
'검색어 기반 뉴스 수집' 스크립트를 그대로 복사 붙여넣기 해서 돌리면
계속 다음과 같이 오류가 떠서 이것을 어떻게 해결하면 좋을 지 몰라서 질문드립니다.
참고로 R 버전은 3.4.2이고 R studio는 1.1.383으로 최신입니다.

Error in if (max == "no result") { : 
  missing value where TRUE/FALSE needed

**Comment by mrchypark** [comment]
@SEUNG-HYE 안녕하세요 https://github.com/forkonlp/N2H4/issues/57 이것때문에 생긴 이슈인거 같습니다. max 값을 가져오지 못하는 문제가 생겼는데, 제가 좀 다른 방법을 찾아봐야 될꺼 같아서 시간이 걸릴듯 합니다. 감사합니다.

**Comment by SEUNG-HYE** [comment]
네 감사합니다^^

2017년 10월 11일 오후 3:21, Chan-Yub Park <notifications@github.com>님이 작성:

**Comment by mrchypark** [comment]
안녕하세요 https://github.com/forkonlp/N2H4/pull/61 내용을 수정하면서 아래 예시 코드도 수정했습니다. 혹시 문제가 생기면 알려주세요 감사합니다.

https://github.com/forkonlp/N2H4/wiki/%EA%B2%80%EC%83%89%EC%96%B4-%EA%B8%B0%EB%B0%98-%EB%89%B4%EC%8A%A4-%EC%88%98%EC%A7%91

**Comment by mrchypark** [comment]
@SEUNG-HYE 안녕하세요, 제가 테스트 하는 동안에는 괜찮은거 같네요. 확인해 주시면 감사하겠습니다.

**Comment by SEUNG-HYE** [comment]
이전 이슈에 올라온 'MaxPage를 못찾네요' 게시글에서 'hymnkim'님이 말씀하신 현상과 동일한 내용의 오류가 나타납니다.

**Comment by mrchypark** [comment]
@SEUNG-HYE https://m.blog.naver.com/PostView.nhn?blogId=carrotcarrot&logNo=220662217154&proxyReferer=https%3A%2F%2Fwww.google.co.kr%2F 이거 참고하세요!
