### ISSUE TITLE
in data.frame 에서 arguments imply differing number of rows: 2, 3 오류가 납니다.

### ISSUE THREAD

**Issue by garam0419** [forkonlp/N2H4#63]
안녕하세요! N2H4 툴을 사용하다 문제가 발생하여 글을 남깁니다!
먼저 다음과 같은 패키지를 만들어주셔서 감사합니다~
현재 올려주신 뉴스키워드를 이용한 기사 추출 예제를 그대로 사용하고 있으며, 키워드와 날짜만 변경한 상태입니다.

strDate<-as.Date("2016-01-04")
endDate<-as.Date("2017-11-06")
qlist<-c("장애인")

Error in data.frame(titles, urls, presses, datetime, edittime, bodies) : 
  arguments imply differing number of rows: 2, 3

크롤링이 잘 진행되다가 다음과 같은 오류가 발생합니다. rows에 해당하는 index는 기사에 따라 다르게 발생하구요~
제가 R은 처음이라 혹시 다음부분에 예외처리를 통해 크롤링이 중단되지 않은채 다음 기사로 넘어갈 수 있는지, 행여나 다른 문제라면 해결 방법을 알려주시면 감사하겠습니다!!ㅎㅎ~

+
![capture1](https://user-images.githubusercontent.com/20810855/32438017-7161e5c8-c32c-11e7-931a-9352f7a68203.PNG)

그리고 혹시 다음과 같이 크롤러가 중간에 멈춘 후 진행되지 않는 문제 또한 종종 발생합니다.
혹시 이문제에 대해서도 해결 방안이 있다면 답변 부탁드리겠습니다.

감사합니다^^~

**Comment by garam0419** [comment]
+죄송합니다. 추가적으로 멈춘 날짜에서 다음날로 날짜를 변경하여 계속 크롤러를 돌려보니 2016년 4월 기사부터 다음과 같은 오류가 또 발생하네요...ㅠㅠ 

[1] "try again max num: https://search.naver.com/search.naver?where=news&query=장애인&ie=utf8&sm=tab_srt&sort=1&photo=0&field=0&reporter_article=&pd=3&ds=2017.11.01&de=2017.11.01&docid=&nso=so%3Ar%2Cp%3Afrom2017-11-01to2017-11-01%2Ca%3Aall&mynews=0&mson=0&refresh_start=0&related=0"

Error in 1:max : NA/NaN argument

**Comment by mrchypark** [comment]
@garam0419 안녕하세요, 코드 전체를 주실 수 있으신가요?

**Comment by mrchypark** [comment]
@garam0419 테스트 해본 결과 16년 3월 8일은 저는 잘 지나가구요. 4월 1일도 괜찮은거 같습니다. 혹시 SessionInfo() 확인해 보실 수 있으신가요?

**Comment by garam0419** [comment]
코드는 Wiki에 나와 있는 것을 그대로 가져와 이용했습니다.
수정한 부분은 Keyword와, 날짜 입니다!
제가 R은 처음 써보아서 SessionInfo()라 함은 정확히 어떤걸 의미하는걸까요~?

+아 그리고 try agin max num 부분의 URL을 눌러보면 크롤러 제한관련 오류 같은데,
혹시 한번에 많은양의 데이터를 수집해서 발생하는 문제일까요? 

install.packages("selectr")
library(curl)
library(rvest)
install.packages("devtools")
devtools::install_github("forkonlp/N2H4")
library(N2H4)

options(stringsAsFactors = F)

success <- function(res){
  cat("Request done! Status:", res$status, "\n")
  #res$content<-iconv(rawToChar(res$content),from="CP949",to="UTF-8")
  res$content<-rawToChar(res$content)
  data <<- c(data, list(res))
}
failure <- function(msg){
  cat("Oh noes! Request failed!", msg, "\n")
}


strDate<-as.Date("2016-04-01")
endDate<-as.Date("2017-11-06")

strTime<-Sys.time()
midTime<-Sys.time()

qlist<-c("장애인")
for (i in 1:length(qlist)){
  dir.create("./data",showWarnings=F)
  dir.create(paste0("./data/news_",qlist[i]),showWarnings=F)
  
  for (date in strDate:endDate){
    date<-as.character(as.Date(date,origin = "1970-01-01"))
    dateo<-gsub("-",".",date)
    dated<-gsub("-","",date)
    print(paste0(date," / ",qlist[i], "/ start Time: ", strTime," / spent Time: ", Sys.time()-midTime," / spent Time at first: ", Sys.time()-strTime))
    midTime<-Sys.time()
    pageUrli<-paste0("https://search.naver.com/search.naver?where=news&query=",qlist[i],"&ie=utf8&sm=tab_srt&sort=1&photo=0&field=0&reporter_article=&pd=3&ds=",dateo,"&de=",dateo,"&docid=&nso=so%3Ar%2Cp%3Afrom",date,"to",date,"%2Ca%3Aall&mynews=0&mson=0&refresh_start=0&related=0")  
    trym<-0
    max<-try(getMaxPageNum(pageUrli, search=T), silent = T)
    while(trym<=5&&class(max)=="try-error"){
      max<-try(getMaxPageNum(pageUrli, search=T), silent = T)
      Sys.sleep(abs(rnorm(1)))
      trym<-trym+1
      print(paste0("try again max num: ",pageUrli))
    }
    if(max=="no result"){
      print("no naver news links this time")
      next
    }
    for (pageNum in 1:max){
      start<-(pageNum-1)*10+1
      print(paste0(date," / ",qlist[i], "/ start Time: ", strTime," / spent Time: ", Sys.time()-midTime," / spent Time at first: ", Sys.time()-strTime))
      midTime<-Sys.time()
      pageUrl<-paste0(pageUrli,"&start=",start)
      tryp<-0
      newsList<-try(getUrlListByQuery(pageUrl), silent = T)
      while(tryp<=5&&class(newsList)=="try-error"){
        newsList<-try(getUrlListByQuery(pageUrl), silent = T)
        Sys.sleep(abs(rnorm(1)))
        tryp<-tryp+1
        print(paste0("try again max num: ",pageUrl))
      }
      if(newsList$news_links[1]=="no naver news"){ 
        print("no naver news links this time")
        next
      }
      
      pool <- new_pool()
      data <- list()
      sapply(newsList$news_links, function(x) curl_fetch_multi(x,success,failure))
      res <- multi_run()
      
      if( identical(data, list()) ){
        pool <- new_pool()
        data <- list()
        sapply(newsList$news_links, function(x) curl_fetch_multi(x,success,failure))
        res <- multi_run()
      }
      
      closeAllConnections()
      
      loc<-sapply(data, function(x) grepl("^http://news.naver",x$url))
      cont<-sapply(data, function(x) x$content)
      cont<-cont[loc]
      
      if(identical(cont,character(0))){ 
        print("no naver news links this time")
        next
      }
      
      titles<-unlist(lapply(cont,function(x) getContentTitle(read_html(x))))
      bodies<-unlist(lapply(cont,function(x) getContentBody(read_html(x))))
      presses<-unlist(lapply(cont,function(x) getContentPress(read_html(x))))
      datetime<-lapply(cont,function(x) getContentDatetime(read_html(x))[1])
      datetime<-sapply(datetime, function(x) (as.character(x)[1]))
      edittime<-lapply(cont,function(x) getContentDatetime(read_html(x))[2])
      edittime<-sapply(edittime, function(x) (as.character(x)[1]))
      
      urls<-sapply(data, function(x) x$url)
      urls<-urls[loc]
      
      datC<-data.frame(titles,urls,presses,datetime,edittime,bodies)
      
      write.csv(datC, file=paste0("./data/news_",qlist[i],"/news_",date,"_",pageNum,".csv"),row.names = F, fileEncoding="UTF-8")
      
    }
  }
}

**Comment by mrchypark** [comment]
@garam0419 코드 감사합니다. 혹시 패키지를 새로 설치 해보셨나요? 방금 주신 코드 저는 문제없이 동작하는 거 같습니다. 혹시 에러가 나면 pageUrli 를 출력해서 저를 보여주실 수 있으신가요?

**Comment by garam0419** [comment]
https://search.naver.com/search.naver?where=news&query=장애인&ie=utf8&sm=tab_srt&sort=1&photo=0&field=0&reporter_article=&pd=3&ds=2016.04.01&de=2016.04.01&docid=&nso=so%3Ar%2Cp%3Afrom2016-04-01to2016-04-01%2Ca%3Aall&mynews=0&mson=0&refresh_start=0&related=0
![capture2](https://user-images.githubusercontent.com/20810855/32442159-bd24e29c-c33d-11e7-8d2c-b5441a265d70.PNG)

URL 눌러 확인해본 결과 오류가 나는 이유는 검색 제한인것 같습니다..ㅎㅎ
혹시 어느정도 크롤링을 해야 제한이 되지 않을지요..

**Comment by mrchypark** [comment]
억;;; 글쎄요.... 그건 조절해봐야 할 것 같습니다ㅠ_ㅠ 검색쪽은 막는 군요... 아마 검색량 제한떄문에 제가 날짜별로 가져오도록 해놨는데, 서버 입장에선 그게 정상 요청을 아니라고 이해하는 것 같습니다... 역시 검색쪽이 어렵네요.

**Comment by mrchypark** [comment]
@garam0419 이건 속도 이슈 인거 같아서 이슈 자체는 닫도록 하겠습니다. 감사합니다.

**Comment by garam0419** [comment]
아 그렇군요. 답변 너무 감사합니다ㅠㅠ 혹시 질문하나만 더 남겨도 될런지요..?
기존 getnavernews.R 패키지의 경우 모든 기사를 분야별 날짜별로 크롤링 할 수 있는 걸로 알고 있는데 이 패키지 또한 혹시 검색량 제한이 생길 수 있을까요..?

**Comment by mrchypark** [comment]
https://github.com/forkonlp/N2H4/wiki/카테고리-리스트내-뉴스-수집  을 확인하시면 모든 기사를 분야별 날짜별로 가져오는 거로 하실 수 있을 것 같습니다. 이건 말씀하신 것 처럼 검색량 제한에서 조금 자유로울 꺼에요.

**Comment by garam0419** [comment]
네 한번 사용해 보겠습니다~ 친절히 답변해주셔서 너무 감사드립니다. 고생하세요^^
