### ISSUE TITLE
네이버 스포츠 뉴스 댓글수집

### ISSUE THREAD

**Issue by xvyaward** [forkonlp/N2H4#64]
안녕하세요? 얼마전에 네이버 스포츠 뉴스 크롤링 관련 질문했던 학생입니다. 결과부터 말하면 현재 스포츠 기사 추출에는 잘쓰고있어서, 감사하단 말씀 드립니다. 그런데 댓글수집은 아직까지 못하고있어 질문드립니다.

1) 찾아보니 네이버 open API를 이용하려면 등록과정을 거치고, 요청 헤더에 클라이언트 정보 등을 추가해야하는 거 같더군요. 
`http://apis.naver.com/commentBox/cbox/web_naver_list_jsonp.json?ticket=sports&templateId=view&pool=cbox2&_callback=jQuery1113020049989799848422_1509795433279&lang=ko&country=KR&objectId=news025%2C0002750844&categoryId=&pageSize=20&indexSize=10&groupId=&listType=OBJECT&page=1&initialize=true&userType=&useAltSort=true&replyPageSize=20&moveTo=&sort=LIKE&_=1509795433280`
 
다음이 스포츠 기사 api의 한 예인데, 네이버 뉴스 댓글수집api랑 종류가 다른 것인가요? 만약 그렇다면 등록을 안해서 사용을 못하는 것인지 궁금합니다.

2) 세부정보만 다르고 같은 종류의 사용가능한 api라면, https://github.com/forkonlp/N2H4/issues/62 여기 62번 이슈처럼 코드를 살짝 바꿔서 진행해봤는데 댓글 수집이 안되더군요. 무엇이 문제인지 알 수 있을까요?

**Comment by mrchypark** [comment]
@xvyaward 안녕하세요, getComment 함수를 입력 url에 sports가 포함되면 sports 댓글을 수집할 수 있게 변경하였습니다. 혹시 테스트해봐주시면 감사하겠습니다.

**Comment by mrchypark** [comment]
@아울러 제목과 내용 쪽 코드 기여해주셔서 감사합니다. 혹시 나중에 여유가 되시면 github pr 주시면 반영하도록하겠습니다. 감사합니다.

**Comment by mrchypark** [comment]
안녕하세요, 1페이지 이상 수집하는 내용에 대해 수정했습니다. https://github.com/forkonlp/N2H4/pull/68
