### ISSUE TITLE
sleep_time 설정 문제

### ISSUE THREAD

**Issue by LeeKwangHo** [forkonlp/N2H4#69]
안녕하세요! 저번에 크롤링 도중 R이 멈추는 현상에 대해서 질문한 사람입니다.

정말 라이브러리 잘 활용하고 있습니다. 감사합니다

다름이 아니라 크롤링 도중 멈추는 현상을 해결하고자 이리저리 굴러봤습니다만 아직 해결을 못하고 있습니다.

의심가는 부분이 getContent에서 Sys.sleep() 을 할때 일어나는 현상인거 같습니다.

그래서 sleep_time 의 default 값을 변경하여 실행을 해보려고 하였으나 현재 코드에서는 Sys.sleep(abs(sleep_time)) 이 아닌 Sys.sleep(abs(rnorm(1))) 으로 되어있어 sleep_time을 변경하여도 변경이 되지 않습니다.

혹시 한번 확인 부탁드려도 될까요?

**Comment by mrchypark** [comment]
안녕하세요 제가 진행하다가 멈췄던 모양이네요ㅠ_ㅠ 확인해보겠습니다.
항상 이렇게 문의주셔서 감사합니다!

**Comment by LeeKwangHo** [comment]
아닙니다! 제가 항상 감사드리고 있습니다.

앞으로도 계속 이슈 발견되면 알려드리겠습니다!
