### ISSUE TITLE
wiki 예제에서 하나의 파일로 저장하는 방식을 추가

### ISSUE THREAD

**Issue by mrchypark** [forkonlp/N2H4#70]
차라리 파일을 합치는 코드를 공유하는게 빠를듯

**Comment by koreanjoker1983** [comment]
안녕하세요. 프로그램 유용히 잘 쓰고 있습니다. 하나의 CSV 파일로 저장하는 방식은 Wiki 예제 어느 곳에 설명돼 있는 것인지요?

**Comment by mrchypark** [comment]
아 이슈가 아직 open 되어 있단 얘기는 아직 진행되지 않았다는 뜻입니다. 문의가 있어 이슈 등록은 해두었는데, 제가 신경을 못쓰고 있네요.ㅎㅎ 혹시 다른 분이 작성해주시면 wiki에 추가하면서 어느 분이 작성한 거라고 써두면 좋을 것 같은데, 아직 도와주신 분이 없습니다.

**Comment by WooyeongKil** [comment]
안녕하세요
프로그램 잘쓰고 있습니다
제가 프로그래밍을 배우는 중이라 아직 짜놓으신 것도 잘못쓰고 있는데, 
확보한 URL을 csv 파일로 넣어서 한번에 크롤링 돌리는 방법을 잘 몰르겠네요
일정 분량을 한번에 크롤링하는 방법을 좀 알려주시면 감사하겠습니다

**Comment by mrchypark** [comment]
https://github.com/forkonlp/N2H4/wiki/%EC%B9%B4%ED%85%8C%EA%B3%A0%EB%A6%AC-%EB%A6%AC%EC%8A%A4%ED%8A%B8%EB%82%B4-%EB%89%B4%EC%8A%A4-%EC%88%98%EC%A7%91

위 케이스에 대해서 append 옵션으로 한 파일에 계속 저장하는 방식으로 수정했습니다. 다른 wiki로 조만간 반영하겠습니다.
