### ISSUE TITLE
getComment로 가져올수 있는 정보 문의

### ISSUE THREAD

**Issue by manmani3** [forkonlp/N2H4#74]
코드상으로는 없는것 같지만 댓글정보 중 그 댓글의 성별을 나타낼 수 있는 속성도 같이 있는지 궁금합니다. 현재 코드에 없다면, 아예 방법이 없을지요?

**Comment by mrchypark** [comment]
getComment(turl, type="list") 로 하시면 전체 정보를 가져올 수 있습니다.
getComment(turl, type="list")$result$graph$gender 에 댓글 성별의 비율은 네이버에서 제공합니다만,

각 댓글의 성별 정보는 제공하지 않습니다.

감사합니다.
