### ISSUE TITLE
카테고리 리스트내 뉴스 수집시 페이지 넘버별로 파일 생성이 아닌 한 파일에 이어서 저장하는방법

### ISSUE THREAD

**Issue by LeeHangseok** [forkonlp/N2H4#75]
카테고리 리스트내 뉴스 수집시 페이지 넘버별로 각각이이 아닌 하나에 이어서 붙일수 없을까요?

**Comment by mrchypark** [comment]
https://github.com/forkonlp/N2H4/issues/70

여기에 대답을 추가하였습니다.
