### ISSUE TITLE
getUrlListByCategory() 함수 반환값

### ISSUE THREAD

**Issue by hyunsooda** [forkonlp/N2H4#79]
<U+C774><U+D6A8><U+C131> <U+C704><U+C6D0><U+C7A5>, KBS <U+CC3E><U+C544> <U+B178><U+B3D9><U+C2DC><U+AC04> <U+B2E8><U+CD95> <U+C548><U+CC29> <U+B2F9><U+BD80>" 이런식으로 유니코드로나와서 쓸수가없는데 작성하신함수보니까 따로인코딩 주는곳은없어보이는데 어떻게해야 한글문서를 읽어들였을떄 온전히받을수잇나요?

**Comment by mrchypark** [comment]
맥 사용자 이시군요
인코딩을  UTF-8 로 설정하시면 됩니다.
Sys.setlocale("LC_ALL", "ko_KR.UTF-8")
