### ISSUE TITLE
cran 등록

### ISSUE THREAD

**Issue by mrchypark** [forkonlp/N2H4#81]
http://r-pkgs.had.co.nz/r.html#r-differences

확인 요

**Comment by mrchypark** [comment]
https://cran.r-project.org/web/packages/N2H4/index.html
https://github.com/forkonlp/N2H4/tree/v0.5.4

**Comment by richardyhong** [comment]
늦었지만 축하드립니다 
수고 많으셨습니다 
-----Original Message-----

**Comment by mrchypark** [comment]
@richardyhong 감사합니다!
