### ISSUE TITLE
Error in UseMethod("unnest_")

### ISSUE THREAD

**Issue by YoungjunNa** [forkonlp/N2H4#83]
OS: macOS Mojave 10.14.2
R: 3.4.4

다음과같은 오류가 발생합니다.

[![asciicast](https://asciinema.org/a/o7O1DvdcYfFx1Dqso5hu3VDiG.svg)](https://asciinema.org/a/o7O1DvdcYfFx1Dqso5hu3VDiG)

**Comment by mrchypark** [comment]
안녕하세요! 이렇게 이슈 등록해주셔서 감사합니다. 현재 댓글 수집 기능은 일반 뉴스만 가능합니다. 현재 시도하신 링크는 스포츠 뉴스입니다. 네이버 뉴스에서 스포츠 뉴스랑 tv 연애는 구조가 달라 따로 작성해야 합니다. 감사합니다.

**Comment by mrchypark** [comment]
스포츠 뉴스에 대해 작성해봐야 겠네요.

**Comment by YoungjunNa** [comment]
답변 감사드립니다 :) 좋은 패키지 개발해주셔서 감사합니다.

**Comment by mrchypark** [comment]
@YoungjunNa 코드를 찾아보니 http만 sports 뉴스를 인지하는 문제가 있었습니다. 수정했으니 사용해봐주세요 감사합니다.

https://github.com/forkonlp/N2H4/commit/922ec667ea1157b7b2d2923505d06ed1eb2c2bee

**Comment by YoungjunNa** [comment]
고맙습니다. 잘 작동하네요~!
