### ISSUE TITLE
혹시 getNewsTrend는 더이상 동작하지 않나요?

### ISSUE THREAD

**Issue by angie48** [forkonlp/N2H4#84]
getNewsTrend('삼성', '2019-03-01', '2019-03-06', onlyPaper=FALSE)

R 초보라, 적혀있는 함수들을 하나하나 해보고 있는데 요거는 어째서인지 자꾸만 숫자가 0으로 떠서요...
위키에 있는 뉴스 트랜드로 그래프 그리는 코드를 그대로 가져와서 해봐도
수치가 0으로만 표기되어, 혹시 해당 함수가 더이상 지원되지 않는 것인지 궁금합니다~

<위에 적힌 코드를 실행 시 나타나는 내용>
 date cnt
1 2019-03-01   0
2 2019-03-02   0
3 2019-03-03   0
4 2019-03-04   0
5 2019-03-05   0
6 2019-03-06   0

**Comment by mrchypark** [comment]
getQueryUrl() 함수에 의존이 있는데, 네이버 뉴스 검색기능이 개편되서 현재는 작동하지 않습니다. ㅜㅠ

시간 내서 고쳐 볼께요 이슈진행해 주셔서 감사합니다!

**Comment by mrchypark** [comment]
https://github.com/forkonlp/N2H4/commit/a6a36079d54afb2605b149c507573ac5d564effe 이 커밋으로 수정하였습니다. 한번 확인해주세요 감사합니다!

재설치 해서 진행해봐주시면 감사하겠습니다.

**Comment by angie48** [comment]
감사합니다! 이제 했더니 그래프도 그려지고 수치도 나오는 것 같아요 ~
