### ISSUE TITLE
안녕하세요. 잘 되지 않아 여쭤봅니다.

### ISSUE THREAD

**Issue by yeonjijeon** [forkonlp/N2H4#85]
안녕하세요. N2H4를 이용한 프로젝트를 만들고 있는 학생입니다.

다름이 아니라, 기능 중 getContent 가 잘 되지 않아 글을 쓰게 되었습니다.
![1](https://user-images.githubusercontent.com/46334767/56633530-82ae4800-6699-11e9-9893-bf185df648bb.png)
개발자님께서 올려주신 WiKi의 기능 설명 중, url을 복사하여

![2](https://user-images.githubusercontent.com/46334767/56633531-82ae4800-6699-11e9-92d4-0df84226bfe6.png)
위와 같이 하였지만 url을 제외한 나머지들은 모두 page is not news section 이라고 나옵니다.
다른 url로도 시도해보았지만 같은 결과가 나오는데
어떻게 해야할지 궁금합니다.

답 부탁드립니다. 감사합니다.

**Comment by mrchypark** [comment]
안녕하세요! 알려주신 덕분에 문제를 파악하고 수정하였습니다.

0.5.1 버전으로 설치하시면 기대하시는 대로 동작할 것입니다. 감사합니다.
