### ISSUE TITLE
네이버 기사 좋아요 데이터

### ISSUE THREAD

**Issue by hamgeonhee** [forkonlp/N2H4#92]
안녕하세요. R을 이용해 네이버 댓글 크롤링 하는 법을 배우던 중 좋은 패키지를 알게되었습니다. 편하게 사용할 수 있게 제공해 주셔서 감사합니다.

한가지 여쭤보고 싶은게 있습니다. 

저는 rvest 패키지를 사용해 우선적으로 제가 댓글을 모으고 싶은 기사 url, 날짜, 기사제목, 언론사, 본문내용 등을 직접 수집하는데 까지는 성공했으나 댓글부분을 긁어오는게 rvest로 하면 자료가 넘어오질 않더라구요. (그래서 다른 방법을 찾아보다 보니 N2H4 패키지를 알게 되어 댓글을 수집 할 수 있었습니다.) 

제가 추가로 얻고 싶은 데이터는 기사 본문 이후에 나오는 감정 클릭 수 (좋아요,훈훈해요,슬퍼요,화나요,후속기사 원해요)인데 이 부분 역시 해당 부분을 긁어오면 모두 '0' 으로 표시되는 문제가 있었습니다. 분명 웹에서 F12눌러 html상으로 확인해보면 클릭 숫자가 적혀있는데도요. 혹시 N2H4 패키지로 해당 기사의 좋아요 카운트를 긁어올 수 있는 방법이 있을까요? 아니면 혹시 다른 방법으로 좋아요 부분 카운트를 긁어오는 방법이 있을까요?

다시한번 좋은 패키지로 편안하게 사용할 수 있게 해주신점 감사드립니다.
![likeit](https://user-images.githubusercontent.com/35475144/65846762-cd836880-e379-11e9-9461-62da4c109e92.png)

**Comment by mrchypark** [comment]
안녕하세요, 좋은 제보 해주셔서 감사합니다.

이건 제가 아마도 기능으로 추가해야 할 것 같네요.

찾아보니

https://news.like.naver.com/v1/search/contents?suppress_response_codes=true&callback=jQuery112404637325143263713_1569843258531&q=NEWS%5Bne_081_0003032561%5D%7CNEWS_SUMMARY%5B081_0003032561%5D%7CNEWS_MAIN%5Bne_081_0003032561%5D&isDuplication=false&_=1569843258532

이 주소로 따로 요청해야 하는 것으로 보입니다.
아마도 동작을 좀더 살펴봐야 할 것 같습니다.

패키지내에 추가해서 알려드리겠습니다.

좋은 기능 요청해주셔서 감사합니다.

**Comment by mrchypark** [comment]
https://github.com/forkonlp/N2H4/commit/6f37538d399b5bfed1dffe5c07aff4388ea9440c

우선 getLike 함수로 구현해보았습니다.

getLike("해당 뉴스기사 url") 입니다.

getLike("https://news.naver.com/main/read.nhn?mode=LSD&mid=shm&sid1=100&oid=001&aid=0011112616") 

이렇게 시도해보시고 알려주세요.

감사합니다.

**Comment by hamgeonhee** [comment]
보내주신 getLike() 함수 사용해보니 너무 잘 작동합니다.
너무 빠르고 정확한 피드백 주셔서 정말 감사드립니다!
