### ISSUE TITLE
entertain.naver.com 에서 댓글 가져오기

### ISSUE THREAD

**Issue by kangkabseok** [forkonlp/N2H4#93]
네이버의 연예뉴스에서 댓글을 가져오려는데 어떻게 하면 되나요?

**Comment by mrchypark** [comment]
안녕하세요, 현재 설계에는 연에 뉴스는 고려되어 있지 않습니다. ㅠ

한번 구조를 살펴보고 반영할 수 있으면 추가하겠습니다.
이렇게 제안주셔서 감사합니다.

**Comment by mrchypark** [comment]
현재 연예 뉴스의 댓글이 폐지 되어 본 이슈를 종료합니다.
